chore: 프로필 페이지에 API 연결
404-DriverNotFound/team-a pull request #101
Opened 2021-08-03 08:46 UTC by cos18

API 연결을 진행했습니다.

추가로 axios에 기본 세팅을 추가해 경로를 간단하게 작성해도 되도록 리펙토링했습니다.

Closed #70

2021-08-03 09:39 UTC, kmin-283 requested changes
고생하셨습니다!!

프로필 관련 동작 모두 잘 되네요!

2021-08-03 09:39 UTC, kmin-283 commented on front/src/components/pages/ProfilePage/ProfilePage.tsx
> +    // }, 2000);
이제 주석을 없애도 될 것 같습니다!

2021-08-03 09:39 UTC, kmin-283 commented on front/src/components/pages/ProfilePage/ProfilePage.tsx
> +    targetUser !== undefined
targetUser가 undefined가 되서 alertCard가 나오는 경우가 있나요??!

유저 id로 존재하지 않는 번호를 써도 profileUserSection이 나타납니다..

2021-08-04 01:00 UTC, cos18 commented on front/src/components/pages/ProfilePage/ProfilePage.tsx
> +    targetUser !== undefined
#100 이슈 확인해주세요. 수정되면 고칠 예정입니다. Todo 추가해놓을게요!

2021-08-04 01:50 UTC, kmin-283 commented on front/src/components/pages/ProfilePage/ProfilePage.tsx
> +    targetUser !== undefined
넵 이슈 확인했습니다!

2021-08-04 06:59 UTC, kmin-283 approved these changes
고생하셨습니다! 👍

2021-08-04 06:59 UTC, merged