feat: Game-end
404-DriverNotFound/team-a pull request #138
Opened 2021-08-06 09:06 UTC by kmin-283

나가기 버튼을 구현하여 게임에서 나가는 경우를 처리하였습니다.

나가는 유저는 기존의 이벤트와 소켓을 모두 정리하고, 새롭게 소켓을 생성하여 연결됩니다.

2021-08-06 16:48 UTC, cos18 requested changes
늦게 확인해 죄송합니다 ㅠㅠ 내일 회의때 뵈요!

2021-08-06 16:48 UTC, cos18 commented on front/src/components/pages/GameListPage/GameListPage.tsx
> +          });
socket_unset type가 있습니다. 그거 활용해주세요.

2021-08-06 16:48 UTC, cos18 commented on front/src/components/organisms/PongGame/PongGame.tsx
> +    history.go(-1);
```suggestion
    history.goBack();
```
go(-1) === goBack() 같은 함수입니다. 더욱 가독성있게 작성하는게 좋을 것 같습니다.

2021-08-06 16:48 UTC, cos18 commented on front/src/components/pages/GameListPage/GameListPage.tsx
> +          userSocket.disconnect();
```suggestion
          userSocket.disconnect();
```
disconnect 하면 offAny 할 필요가 있나요?

2021-08-06 16:48 UTC, cos18 commented on front/src/components/pages/GameListPage/GameListPage.tsx
> +          history.go(0);
이건 왜 넣으신건가요? 뒤로가기만 되면 해결되지 않나요?

2021-08-07 05:46 UTC, kmin-283 commented on front/src/components/pages/GameListPage/GameListPage.tsx
> +          userSocket.disconnect();
disconnect시에 이벤트들이 모두 사라지는지 어떻게 되는지 몰라서 작성해두었는데 없애도 될 것 같습니다!

2021-08-07 13:12 UTC, kmin-283 commented on front/src/components/pages/GameListPage/GameListPage.tsx
> +          history.go(0);
하루종일 이것만 보다가 드디어 해결했습니다!

2021-08-07 13:55 UTC, cos18 approved these changes
LGTM!

2021-08-07 13:55 UTC, merged