feat: connect game mode api
404-DriverNotFound/team-a pull request #158
Opened 2021-08-09 04:30 UTC by kmin-283

game mode 설정에 맞춰 변경합니다.

2021-08-09 15:54 UTC, cos18 requested changes
루트폴더 경로 yarn 파일 지워주세요!

2021-08-10 02:39 UTC, cos18 reviewed
-

2021-08-10 02:41 UTC, cos18 requested changes
프론트의 yarn.lock이 아니라 루트 폴더의 yarn 파일을 말하는거였어요... PR의 파일 체인지 확인해주세요.

프론트 yarn.lock 지우는거 취소하시고 루트 폴더 yarn 파일 지워주세요

2021-08-10 06:10 UTC, kmin-283 commented
> 프론트의 yarn.lock이 아니라 루트 폴더의 yarn 파일을 말하는거였어요... PR의 파일 체인지 확인해주세요.
> 
> 프론트 yarn.lock 지우는거 취소하시고 루트 폴더 yarn 파일 지워주세요

앗 그렇군요... 복구해서 다시 작업하겠습니다

2021-08-10 08:28 UTC, cos18 approved these changes
LGTM

2021-08-10 08:28 UTC, merged