feat: token만료시 다시 로그인하도록 수정
404-DriverNotFound/team-a pull request #169
Opened 2021-08-10 09:56 UTC by kmin-283

로그인 시 설정된 토큰 만료 시간인 2시간만큼 타이머를 동작시켜서 2시간이 지나면 다시 로그인 하도록 구성하였습니다.

2021-08-10 14:05 UTC, cos18 requested changes
토큰 invalid는 이런식으로 처리하면 안되는걸로 알고있습니다... 현재 토큰이 localstorage에 저장해서 사용하기 떄문에 제가 새 탭을 열어도, 아예 껐다 켜도 로그인이 되는식으로 구현되었는데, 그 상황에서는 interval이 남아있지 않기 때문입니다.

따라서 일단 api 통신 시도 -> 실패하면 재로그인 요청 이런 방식으로 구현해야 위의 문제들을 해결할 수 있습니다. 확인하시고 혹시 다른 방법이 있다면 의견 남겨주세요.

2021-08-11 05:00 UTC, cos18 requested changes

2021-08-11 05:00 UTC, cos18 commented on front/src/utils/api/fetch.ts
> +  url: string, body?: unknown,
현재 contextAPI의 payload를 보시면 들어올 수 있는 타입들이 or 처리되어있는데 이런 형식으로 바꾸셔서 올릴 수 있을까요?

2021-08-11 05:00 UTC, cos18 commented on front/src/utils/api/fetch.ts
> +  url: string, body: unknown,
여기도 마찬가지입니다!

2021-08-11 05:05 UTC, kmin-283 commented on front/src/utils/api/fetch.ts
> +  url: string, body?: unknown,
스웨거에 있는 형식대로 맞춰서 변경하겠습니다!

2021-08-11 05:42 UTC, cos18 approved these changes
LGTM! 컨플릭트만 수정하시고 머지하시면 될거같아요~

2021-08-11 05:49 UTC, merged