Avatar
404-DriverNotFound/team-a pull request #18
Opened 2021-07-14 07:46 UTC by kmin-283

Avatar  컴포넌트
# 사진이 없거나 문제가 발생했을 때 나타날 수 있는 기본 화면
![8](https://user-images.githubusercontent.com/63279334/125583472-1e612550-c0e9-4ea5-934b-0ee1e889aad4.png)

# 특정한 이미지를 아바타로 등록한 경우
![9](https://user-images.githubusercontent.com/63279334/125583476-f9ff8d53-edf5-4b53-9376-716044717e62.png)

# 주의사항
리눅스 이미지가 Avatar 디렉토리에 있으므로 확인을 마친 후 삭제해야 합니다.

2021-07-14 10:46 UTC, cos18 requested changes

2021-07-14 10:46 UTC, cos18 commented on front/src/components/atoms/Avatar/Avatar.stories.tsx
> +};
이런식으로 static 파일을 스토리로 사용하는 것 보단 실제 사용하는 42api 프로필 사진 사용하는거도 좋을 것 같아요.

https://cdn.intra.42.fr/users/medium_sunpark.jpg 요런 링크 쓰면 좋을것같아요.

2021-07-14 10:46 UTC, cos18 commented on front/src/interfaces/atoms/Avatar/IAvatar.ts
> +import React, { MouseEvent } from 'react';
```suggestion
import { MouseEvent } from 'react';
```

React를 사용하지 않는다는 eslint waring이 있습니다.

2021-07-14 10:46 UTC, cos18 commented on front/src/components/atoms/Avatar/Avatar.tsx
> +  return <MaterialAvatar src={src} className={classes[size]} onClick={onClick} />;
onClick이 들어간 경우 css cursor: pointer를 쓰면 좋을 것 같습니다.

참고) https://github.com/404-DriverNotFound/team-a/blob/0de8dda312ea5d21faac7da0f9337d9673caf6c8/front/src/components/atoms/Typo/Typo.tsx#L8

2021-07-14 10:46 UTC, cos18 commented on front/src/components/atoms/Avatar/Avatar.tsx
> +  },
중복된 margin이나 추가될 cursor를 styled-components로 뺴주면 좋을거같아요.

2021-07-14 11:44 UTC, kmin-283 commented on front/src/components/atoms/Avatar/Avatar.stories.tsx
> +};
오 생각못했는데 좋네요!

2021-07-14 13:41 UTC, cos18 requested changes

2021-07-14 13:41 UTC, cos18 commented on front/src/components/atoms/Avatar/Avatar.tsx
> +    cursor: 'pointer',
onclick이 있을때 없을때 구분해서 cursor 값을 할당해야합니다
onclick이 없는데 커서가 바뀌면 안되기 때문입니다!

2021-07-14 15:35 UTC, kmin-283 commented
```
interface StyleProps {
  onClick?: (event: MouseEvent<HTMLDivElement>) => void;
}
```

아바타에서 makeStyle에서 사용되는 인터페이스를 만들어야했는데

이것도 interface/atoms에 넣는게 맞을까요?

2021-07-15 02:41 UTC, cos18 approved these changes
LGTM👍

2021-07-15 02:41 UTC, merged