Molecules/table item container
404-DriverNotFound/team-a pull request #34
Opened 2021-07-16 09:09 UTC by kmin-283

# tableItemContainer
## online시
![4](https://user-images.githubusercontent.com/63279334/125923217-cdb718fa-7d41-498b-b352-56d112a5edfe.png)
## offline시
![3](https://user-images.githubusercontent.com/63279334/125923223-2fe14f9a-3e72-4894-ab59-651c5b49db9f.png)

2021-07-17 02:24 UTC, cos18 commented
작업이 완료된 PR인가요? 리뷰 지정이 안되어있네요

2021-07-17 05:49 UTC, cos18 requested changes
추가로 왜 Action이 계속 실패하는지 확인해봐야될것같아요. 아마 맨 처음 제목을 작성할 때 제목도 커밋메세지로 들어가 fail로 뜨는 것 같은데, 다음 커밋하시고 한번 상황을 봐야될거같네요.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +            </Button>
일반 버튼이 아니라 iconbutton으로 바꾸는거 어떻게 생각하시나요? 사용자의 브라우저의 폭이 작은 경우 버튼은 폭을 많이 차지해 깨질 것 같습니다.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +  src, name, isOnline, onClick,
1. 이 컨테이너를 클릭했을 때 프로필 페이지로 들어가는 다른 onclick이 필요할 것 같습니다. 이때 버튼이 클릭되었을 땐 추가되는 onclick이 실행되면 안됩니다.
2. 프롭 `onClick`의 이름을 `onButtonClick`과 같이 더욱 구체적이였으면 좋겠습니다. 이 컨테이너 전체의 onclick으로 오해할 것 같습니다.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +const TableItemContainer = ({
이 아이템은 친구 목록에 대한 아이템이니 친구라는 내용이 네이밍에 들어갔으면 좋겠습니다. 지금 네이밍으로는 다른 곳에서도 혼용할 수 있는 아이템으로 보입니다.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/atoms/CheckBox/CheckBox.tsx
> +export default CheckBox;
다른 브랜치에 들어가있고 이미 머지된 내용은 제거해주세요.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.stories.tsx
> +  // eslint-disable-next-line max-len
max-len lint는 지켜주세요. fix 옵션을 넣으면 알아서 해결될거에요.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +                <p className={`${classes.noMargin} ${classes.type}`}>이름</p>
아이템을 하나만 볼땐 적혀있는 내용을 설명하는 p 태그가 있으면 좋지만 이 아이템이 수십개 수백개가 되면 불필요한 요소가 되어버립니다. 현재 적혀있는 이름 / 상태 글자 그 자체는 없어도 충분히 사용자가 추측하여 그 의미를 알 수 있기 때문에 빼도 괜찮을것같습니다.

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +  src, name, isOnline, onClick,
위 커멘트의 1번 내용을 좀 생각해봤는데 두가지 방안이 있을 것 같아요.

1. 위에서 언급한대로 이 컨테이너 전체에 onclick을 부여해 클릭하면 프로필에 들어가도록 만든다. 이때 친구삭제 버튼을 클릭했을 때엔 프로필로 들어가면 안된다.
2. 프로필 들어가는 버튼을 따로 만들어 친구 삭제 버튼 옆에 둔다. 이땐 버튼에게만 onclick 부여하면 된다.

둘중에 고려하셔서 넣으면 될거같아요!

2021-07-17 05:49 UTC, cos18 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +              </Grid>
className을 너무 남발하여 사용하는 것 보단 간단한 컴포넌트 두개를 만들어서 isOnline 조건에 따라 넣는 식으로 만들어주세요.

2021-07-17 06:57 UTC, kmin-283 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +            </Button>
좋습니다!

2021-07-17 08:08 UTC, cos18 commented
@kmin-283 추가로 수정하실때 offline 글씨는 느낌에 맞게 회색으로 처리하는건 어떨까요?

2021-07-17 10:12 UTC, cos18 commented
지금 늦게 확인했는데 브랜치를 잘못 따신거같네요... 브랜치 수정이 필요합니다 ㅠ

2021-07-17 10:19 UTC, kmin-283 commented
> 지금 늦게 확인했는데 브랜치를 잘못 따신거같네요... 브랜치 수정이 필요합니다 ㅠ

어 molecules아닌가요???

2021-07-17 10:21 UTC, kmin-283 commented on front/src/components/molecules/TableItemContainer/TableItemContainer.tsx
> +  src, name, isOnline, onClick,
1번으로 진행하겠습니다~

2021-07-19 00:47 UTC, cos18 requested changes
추가적으로, main 머지를 최대한 지양해주세요. 저번에는 github action을 적용하기 위해 일회성으로 언급한 것이고, PR을 관리하는 경우에는 머지를 하게되면 브랜치가 꼬일 수 있습니다.

2021-07-19 00:47 UTC, cos18 commented on front/src/components/molecules/FriendInfoContainer/FriendInfoContainer.tsx
> +                  : (<OfflineGrid><Typo variant="h6">{onlineState}</Typo></OfflineGrid>)
```suggestion
                isOnline ? <OnlineGrid /> : <OfflineGrid />
```

OnlineGrid, OfflineGrid의 컴포넌트 차일드에 Typo도 같이 넣어서 정의했으면 좋을 것 같습니다.
현재 코드에서 결국 onlineState라는 값 자체도 isOnline에 대해 정의됨으로 이를 중복 언급하는 것을 피하면 더 좋을 것 같습니다.

2021-07-19 00:47 UTC, cos18 commented on front/src/components/molecules/FriendInfoContainer/FriendInfoContainer.tsx
> +const RootContainer = styled(Grid)({
RootContainer도 클릭할때 이벤트가 작동됨으로 cursor: pointer를 넣어주세요.

2021-07-19 00:47 UTC, cos18 commented on front/src/components/molecules/FriendInfoContainer/FriendInfoContainer.tsx
> +  '&:hover ~ div': {
hover를 사용해 그리드 시스템이 깨져보입니다. hover 디자인을 보니 material ui의 [툴팁](https://material-ui.com/components/tooltips/)을 사용하면 좋을 것 같습니다.

2021-07-19 04:38 UTC, cos18 approved these changes
친구 제거 버튼 위치가 많이 애매해 이를 수정해 마무리했습니다. 수고하셨습니다!

2021-07-19 04:38 UTC, merged