Molecules/black list,total info container
404-DriverNotFound/team-a pull request #40
Opened 2021-07-19 06:50 UTC by kmin-283

# blackListInfoContainer
![2](https://user-images.githubusercontent.com/63279334/126113435-dcc5873a-6747-4c98-9adf-da2936775f78.png)

![5](https://user-images.githubusercontent.com/63279334/126113897-d3e1a959-3eca-419d-a8bb-b7638721376b.png)

# TotalInfoContainer

![2](https://user-images.githubusercontent.com/63279334/126115363-6489e8cd-338d-456f-986f-349bfbbf4b87.png)

![3](https://user-images.githubusercontent.com/63279334/126115366-35ec33d1-0955-4425-a6cf-bf3967cfa362.png)

# 주의사항
점수, 승, 패에는 제한이 있어야 할 듯 합니다.
![6](https://user-images.githubusercontent.com/63279334/126115210-fe896e3d-9554-4b4c-96fb-934428551abc.png)
최대 점수, 승패의 크기를 넘어가게 되면 모양이 깨집니다.

2021-07-19 10:48 UTC, cos18 requested changes
추가로 브랜치명을 너무 길게 작성하시는 것 같아요. 또한 브랜치명에 comma (,)를 사용하시는 것을 지양해주세요.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/atoms/IconButton/IconButton.tsx
> +import LockOpen from '@material-ui/icons/LockOpen';
이렇게 계속 하나하나 추가하실거면 지금 현재 쓰지 않는 아이콘은 지워주세요.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/BlackListInfoContainer/BlackListInfoContainer.tsx
> +            <UnblockUserGrid unblockUser={unblockUser} />
friend info container를 보시면 제가 오른쪽 여백이 최대한 없게 수정했습니다. 지난번 디자인도 그렇고 지금 디자인도 오른쪽에 여백이 있어 컨테이너가 불안해보입니다. friend쪽 보시면서 수정해주세요.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/BlackListInfoContainer/BlackListInfoContainer.tsx
> +  src, name, showUserProfile, unblockUser,
사용자가 블랙리스트에 있는 사용자의 프로필을 보러 클릭할까요? kmin님의 의견이 궁금합니다.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/TotalInfoContainer/TotalInfoContainer.tsx
> +              isOnline ? <OnlineGrid /> : <OfflineGrid />
친구 목록에 있는 onlinegrid, offlinegrid랑 같다면 이를 새로운 atom으로 만들어 리펙토링하면 더 좋을 것 같습니다.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/BlackListInfoContainer/BlackListInfoContainer.tsx
> +  <>
저번에도 이야기했지만 태그가 한개만 있으면 fragment가 필요없습니다. 해당내역 수정 부탁드립니다.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/TotalInfoContainer/TotalInfoContainer.stories.tsx
> +const FriendInfoContainerTemplate: Story<TotalInfoContainerProps> = ({
컴포넌트에 맞는 변수명 설정 부탁드립니다.

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/TotalInfoContainer/TotalInfoContainer.stories.tsx
> +const FriendInfoContainerTemplate: Story<TotalInfoContainerProps> = ({
다른 스토리보드 변수들이 다 같습니다

2021-07-19 10:48 UTC, cos18 commented on front/src/components/molecules/TotalInfoContainer/TotalInfoContainer.tsx
> +const TotalInfoContainer = ({
```suggestion
const UserInfoContainer = ({
```
Total 이라는 용어가 현재 컨테이너에 적절하지 않습니다. 유저라는 뜻을 변수명에 넣으면 어떨까요?

2021-07-19 10:49 UTC, cos18 commented
제목도 커밋 규칙에 맞게 작성해주세요. Github Action이 PR 제목도 확인합니다.

2021-07-19 12:43 UTC, kmin-283 commented on front/src/components/molecules/BlackListInfoContainer/BlackListInfoContainer.tsx
> +  src, name, showUserProfile, unblockUser,
차단해제하기전까진 볼 필요가 없어보이네요!

2021-07-19 13:23 UTC, kmin-283 commented on front/src/components/molecules/TotalInfoContainer/TotalInfoContainer.tsx
> +const TotalInfoContainer = ({
좋은것같습니다.

2021-07-19 13:31 UTC, kmin-283 commented
> 제목도 커밋 규칙에 맞게 작성해주세요. Github Action이 PR 제목도 확인합니다.

커밋 제목만을 적을 때는 통과가 되는데 추가로 커밋 내용안에 바디나 푸터를 넣었을 때 그렇게 된 것 같습니다. ㅎㅎ..

2021-07-20 00:21 UTC, cos18 approved these changes
LGTM

2021-07-20 00:21 UTC, merged