Organism/info list
404-DriverNotFound/team-a pull request #45
Opened 2021-07-20 08:24 UTC by kmin-283

# infoList

![2](https://user-images.githubusercontent.com/63279334/126286829-ee51ecbf-0427-4b0d-87ed-8eb2211ec4e1.png)

1. 컨테이너들이 조금씩 떨어져서 보일 수 있도록 디자인을 조금 수정했습니다.
2. 데이터를 비 동기적으로 받아올 수 있도록 storybook에 구현해보았습니다.

# 주의사항
InfoList 상단에 console, alert를 무시하는 eslint가 있으므로 나중에 삭제해야합니다.

주석 처리된 부분은 나중에 구현해야 될 항목입니다.

2021-07-20 09:50 UTC, cos18 requested changes

2021-07-20 09:50 UTC, cos18 commented on front/src/interfaces/organisms/InfoList/IInfoList.ts
> +export type ListType = '전체 유저' | '친구' | '차단 유저';
영어로 정의해주세요

2021-07-20 09:50 UTC, cos18 commented on front/src/components/organisms/InfoList/InfoList.stories.tsx
> +import FriendInfoList from './InfoList';
```suggestion
import InfoList from './InfoList';
```
네이밍 수정해주세요

2021-07-20 09:50 UTC, cos18 commented on front/src/components/organisms/InfoList/InfoList.stories.tsx
> +  component: FriendInfoList,
```suggestion
  title: 'Organisms/InfoList',
  component: InfoList,
```

2021-07-20 09:50 UTC, cos18 commented on front/src/components/organisms/InfoList/InfoList.stories.tsx
> +};
Storybook을 확인해보니 현재 3개의 스토리가 template으로 구현되어있어 하단 컨트롤에서도 조작이 가능합니다.
이를 둘중에 하나로 수정하는게 좋아보입니다.

- 한개의 스토리를 만들어 컨트롤을 통해 3가지 타입을 테스트할수 있게 한다
- 템플릿이 아니라 일반 컴포넌트 렌더링 방식으로 스토리 3개를 만든다

추가로 만약 스토리 3개를 만든다고 하면 Basic은 안붙어도 될거같아요. `FriendInfoList`, `BlackListInfoList`, `UserInfoList`로 충분해 보입니다.

2021-07-20 09:50 UTC, cos18 commented on front/src/components/organisms/InfoList/InfoList.tsx
> +  };
유저 프로필의 경우에도 아이디를 기반으로 한 라우팅이 필요할 수 있습니다. 혹시 어떤 식으로 유저별 프로필을 띄우는 식으로 구현할려 하시나요?

2021-07-20 09:50 UTC, cos18 commented on front/src/components/organisms/InfoList/InfoList.tsx
> +  };
```typescript
function showUserProfile(id: number) => {
  return function onUserItemClicked() => {
    // Implementation
  }
}

// 사용시
<FriendInfoContainer ... showUserProfile={showUserProfile(id)} />
```
사실 이렇게 함수를 리턴해 클로저 형식으로 사용해도 괜찮은데, 원하시는 방식대로 통일하는게 좋을 것 같아요.

2021-07-21 03:57 UTC, kmin-283 commented on front/src/components/organisms/InfoList/InfoList.tsx
> +  };
와우 안그래도 변수를 2개씩넘기고 그랬는데 이 방법이 훨씬 더 좋은 것 같습니다.
감사합니다!!

2021-07-21 04:36 UTC, cos18 approved these changes
LGTM!

2021-07-21 04:36 UTC, merged