chore: DM, 채널 관련 목록 아이템 구현
404-DriverNotFound/team-a pull request #63
Opened 2021-07-23 09:09 UTC by cos18

#49 이슈를 해결하며 나온 문제들도 같이 수정했습니다.
구현 외 수정/보완된 사항들은 다음과 같습니다.
- 컴포넌트 이름을 더욱 단순하게 변경했습니다.
- 아바타 컴포넌트의 옵션으로 online / offline 뱃지를 보여주도록 만들었습니다.
- 목록 아이템의 컨테이너를 따로 컴포넌트로 분리했습니다.
- 타이포 컴포넌트의 display 프롭이 작동되지 않는 오류를 수정했습니다.

Closed #49

2021-07-23 11:03 UTC, kmin-283 requested changes
정말 많은 작업을 하시느라 고생 많으셨습니다...!

맡으신 작업이 너무 많으신게 죄송해서
부담 덜어드릴 수 있게 노력해보겠습니다!

2021-07-23 11:03 UTC, kmin-283 commented on front/src/interfaces/utils/api/IChannel.ts
> +}
채널을 만든사람을 operator 라고 하고, operator가 지정한 admin들이 있을 수 있고

채널 자체도 id를 갖고 있어야 오른쪽 채팅 페이지에 무엇을 보여줄지 식별하기 용이할 것 같습니다.

그리고 채널에 들어있는 유저 정보 자체가 있어야 그 유저의 이름이나 사진 등을 활용할 수 있을 것 같기도 합니다.

```suggestion
export default interface ChannelType {
  id: number;
  name: string;
  isPrivate: boolean;
   operator: number;
  admins: number[]; 
  members: IUserData[];
  size: number;
}
```

2021-07-23 15:23 UTC, cos18 commented on front/src/components/molecules/DMListItem/DMListItem.tsx
> +    </ListItemContainer>
적어주신 내용이 이해가 안되는데, 수정을 하셔도 오른쪽 공백은 같이 나오지 않나요? 그리고 온라인 배지를 없에신 이유가 따로 있나요?

2021-07-23 15:23 UTC, cos18 commented on front/src/interfaces/molecules/JoinChannelListItem/IJoinChannelListItem.ts
> +  showChannelSettings: (event: React.MouseEvent<Element, MouseEvent>) => void;
넵 요건 수정하겠습니다!

2021-07-23 15:26 UTC, cos18 commented on front/src/interfaces/utils/api/IChannel.ts
> +}
음 일단 최대한 쓰이는 데이터 위주로만 타이핑을 해놔서 현재 쓰지 않는 항목에 대해서는 따로 정의해두지 않았습니다. 차피 백엔드에서 네이밍이 달라지면 이를 변경해야 되서 더 불편해질것 같은 느낌도 있고 해서요. 추가적으로 필요한 데이터는 추후 정의하는 식으로 남겨두었습니다. 이후 해당 내용이 필요하면 정의할 예정입니다.

2021-07-23 15:39 UTC, cos18 commented
@kmin-283 리뷰하신 내용 커멘트 달아놨으니 확인 부탁드립니다!

2021-07-24 10:13 UTC, cos18 commented
@kmin-283 아까 이야기한 내용 수정했습니다~

2021-07-24 10:22 UTC, kmin-283 approved these changes
수고 많으셨습니다!

2021-07-24 10:22 UTC, merged