feat: Page/profile edit
404-DriverNotFound/team-a pull request #85
Opened 2021-07-28 05:34 UTC by kmin-283

# profle-edit 페이지
![4](https://user-images.githubusercontent.com/63279334/127269102-0431b59f-a79f-4a81-93e7-e11bba2dc410.png)

2021-07-28 08:48 UTC, cos18 requested changes

2021-07-28 08:48 UTC, cos18 commented on front/src/components/pages/ProfilePage/ProfilePage.tsx
>      console.log('onProfileEditClicked');
구현이 완료된 함수의 콘솔로그는 지워주세요.

2021-07-28 08:48 UTC, cos18 commented on front/src/utils/api/UserContext.tsx
> +    image: 'https://cdn.intra.42.fr/users/medium_sunpark.jpg',
테스트용으로 해놓은건 아는데 이렇게 기본 context를 임의로 바꾸면 안됩니다. api 통신해서 가져오면 값이 들어오지 않나요?

2021-07-28 08:48 UTC, cos18 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            </Button>
취소버튼이 있는게 좋을까요? 뒤로가기나 메뉴버튼으로 충분히 나갈 수 있는데 필요하다면 남겨나도 괜찮은것같아요.

2021-07-28 08:48 UTC, cos18 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            <CheckBox name="two-fa" defaultChecked={twoFA} onChange={toggle2FA} />
채널의 비공개 체크박스처럼 체크가 되었을때 사용자의 이메일을 받는 form이 있어야 합니다.

2021-07-28 12:16 UTC, kmin-283 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            </Button>
그러면 이 부분은 나중에 필요하다고 생각되면 추가하는게 낫겠습니다!

2021-07-28 12:27 UTC, kmin-283 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            <CheckBox name="two-fa" defaultChecked={twoFA} onChange={toggle2FA} />
이메일은 어디에 사용되나요? 인비전에 있는 프로필 항목에서 보이지 않는데...

2021-07-28 12:30 UTC, cos18 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            <CheckBox name="two-fa" defaultChecked={twoFA} onChange={toggle2FA} />
@kmin-283 2fa 키가 이메일을 통해 전송되기 때문에 필요합니당

2021-07-28 12:31 UTC, kmin-283 commented on front/src/utils/api/UserContext.tsx
> +    image: 'https://cdn.intra.42.fr/users/medium_sunpark.jpg',
아하 맞네요! 값이 정상적으로 들어옵니다~

2021-07-28 12:44 UTC, kmin-283 commented on front/src/components/organisms/ProfileEditForm/ProfileEditForm.tsx
> +            <CheckBox name="two-fa" defaultChecked={twoFA} onChange={toggle2FA} />
아하! 그렇군요 이해됐습니다 ㅎㅎ!!

2021-07-28 13:32 UTC, cos18 requested changes

2021-07-28 13:32 UTC, cos18 commented on front/src/interfaces/utils/api/IUserContext.ts
> +  email: string;
2FA가 꺼저있을 땐 이메일이 없을 수 있습니다.

2021-07-28 13:32 UTC, cos18 commented on front/src/interfaces/utils/api/IUserContext.ts
> +  email: string;
이메일 예시 추가한 파트는 커밋 리버트하고 만들어야될거같아요

2021-07-28 13:36 UTC, kmin-283 commented on front/src/interfaces/utils/api/IUserContext.ts
> +  email: string;
유저 데이터를 받을 때 이메일이 항상 오는데 2fa가 꺼져있는 경우에 이걸 받지 않아야 하나요?

2021-07-28 16:01 UTC, cos18 commented on front/src/interfaces/utils/api/IUserContext.ts
> +  email: string;
일단 이메일을 nullable하게 수정해주시고 예시 수정하신건 다 리버트하는게 좋을 것 같아요. 분명 가입시 이메일을 받는 절차가 없기 떄문에 없을 수도 있어 애매하네요.

2021-07-29 00:56 UTC, kmin-283 commented on front/src/interfaces/utils/api/IUserContext.ts
> +  email: string;
넵 알겠습니다~

2021-07-29 04:37 UTC, cos18 approved these changes
LGTM!

2021-07-29 04:48 UTC, merged