feat: api/community get list
404-DriverNotFound/team-a pull request #88
Opened 2021-07-30 02:16 UTC by kmin-283

커뮤니티 페이지에서 백엔드와의 통신을 통해 데이터를 받아옵니다.

현재 임시로 커뮤니티 페이지의 모든 유저 페이지에서 자신을 클릭하면

친구 데이터, 블랙리스트 데이터를 생성하여 받아옵니다.

2021-07-30 11:05 UTC, cos18 requested changes

2021-07-30 11:05 UTC, cos18 commented on front/src/components/organisms/CommunityInfoList/CommunityInfoList.tsx
> +    // const { id } = infoItem;
아이디만 들어온다면 이를 /users/{id} 로 조회해 그 정보를 사용해야 합니다.

2021-07-30 11:05 UTC, cos18 commented on front/src/interfaces/organisms/CommunityInfoList/ICommunityInfoList.ts
> +export type ListType = '' | 'friend' | 'blackList';
user를 비운 이유가 있나요?

2021-07-30 11:05 UTC, cos18 commented on front/src/components/pages/CommunityPage/CommunityPage.tsx
> +        },
https://github.com/404-DriverNotFound/team-a/blob/f1f3c7daff8748d7ac1034a4f96076136609922e/front/src/utils/api/auth.ts#L25

이건 이미 axios default로 처리해놓았습니다. 추가 안하셔도 되요. 혹시 에러가 나나요?

2021-07-30 11:05 UTC, cos18 commented on front/src/components/pages/CommunityPage/CommunityPage.tsx
> +      const res = await axios.get(`${process.env.REACT_APP_API_URL}/community/${listType}`, {
이렇게 사용하기 위해 user를 비워둔것 같은데, 가독성의 가장 큰 감점 포인트는 코드를 읽으면서 의문이 들 때입니다. 이를 getlist 함수 내부에서 따로 처리하거나 하시는게 좋을것같아요.

2021-07-30 11:05 UTC, cos18 commented on front/src/components/pages/CommunityPage/CommunityPage.tsx
> +      return res.data as IUserData[];
지금 리턴값이 전체 유저 목록이냐 아니냐에 따라 달라지는데, 이를 따로 설정해야되니 결국 함수를 두개 만드는게 좋을 것 같습니다.

2021-07-30 11:16 UTC, cos18 commented on front/src/components/organisms/CommunityInfoList/CommunityInfoList.tsx
>      // history.push('/profile');
showUserProfile 함수는 유저 아이템을 클릭되었을 때 실행되는 함수입니다. history.push를 써서 /profile/{id}로 보내줘야 합니다.

2021-07-31 15:28 UTC, kmin-283 commented on front/src/components/pages/CommunityPage/CommunityPage.tsx
> +      return res.data as IUserData[];
지금 api에 따라 결과 값이 다르게 들어오고 community-list에서는 type에 따라 받아온 값을 다르게 그려주는 상황입니다!

혹시 어떤 것을 따로 설정해야 해서 함수를 두 개 만들어야하는건가요??

2021-08-01 04:52 UTC, cos18 commented on front/src/components/organisms/CommunityInfoList/CommunityInfoList.tsx
> +      </Grid>
이거 혹시 가운데정렬로 바꾸실수 있으신가요?

2021-08-01 04:53 UTC, cos18 commented on front/src/components/pages/CommunityPage/CommunityPage.tsx
> +      return res.data as IUserData[];
이때 작성했던 것은 컨트롤러마다 나오는 결과물(리턴값)이 달라 함수를 두개 만들어야되지 않나 생각했는데 백엔드측에서 결과를 같게 보낸다고 하면 이를 유지해도 괜찮을것같네요!

2021-08-01 04:56 UTC, cos18 approved these changes
가운데정렬은 한번 보시고 안해도 괜찮을거같다 싶으시면 머지 부탁드립니다! 수고하셨어요!

2021-08-01 05:03 UTC, merged

2021-08-01 05:03 UTC, cos18 commented
@kmin-283 지금 유저타입 리펙토링 때문에 선머지하고 리펙토링 진행할게요!