Text input
404-DriverNotFound/team-a pull request #9
Opened 2021-07-13 09:36 UTC by kmin-283

![6](https://user-images.githubusercontent.com/63279334/125429203-e511a906-a5d2-4b72-a278-5b086336aa78.png)
![7](https://user-images.githubusercontent.com/63279334/125429211-3363d418-cd35-448d-a685-3c6013e6bf04.png)

- [x] 일반 입력폼
- [x] 비밀 번호 입력폼 
- [x] 에러 발생 폼

2021-07-13 11:17 UTC, cos18 requested changes

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +const TextInput = (props: TextInputProps) => {
추가로 input 값의 처리를 도와주는 onChange 비스무리한게 필요합니다

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +    <>
태그 하나로 묶는거라면 Fragment가 필요없습니다

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +      <form className={classes.root} noValidate autoComplete="current-password">
해당 form 태그로 묶을 이유가 있나요? className에 적용되는 스타일은 TextField에 직접 넣으면 되고, noValidate, autoComplete는 이 컴포넌트 연관이 없는 것 같습니다.

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +          label={props.type ?? "standard"}
라벨은 타입과 무관하게 작성해야 합니다. 입력받은 값이 닉네임이거나 체팅일 수 있습니다. 이에 대해 알려주는게 라벨입니다.

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +          type={props.type ?? ""}
타입이 공백일 수 있나요? 문서에선 TextField의 type은 HTML5에서의 타입이여야 한다고 적혀있습니다.

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +          id={idByCategory(props.type)}
HTML에서 id는 같은 값이 존재할 수 없습니다. 문서 확인해주세요.

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.stories.tsx
> +      color: theme.palette.text.primary,
아마 기본 컬러는 지정하지 않아도 설정될겁니다. 위 값은 없어도 적용됩니다.

2021-07-13 11:17 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.stories.tsx
> +  return (
스토리보드에 값이 바뀔떄마다 Actions에 변경된 값을 출력하도록 만들면 테스트하는데 더 좋을 것 같습니다.

2021-07-13 15:09 UTC, kmin-283 commented on front/src/components/atoms/TextInput/TextInput.tsx
> +      <form className={classes.root} noValidate autoComplete="current-password">
문서를 보고 따라서 작성하다가 같이 작성해야 하는걸로 판단했습니다. 지워보니 없어도 되네요!

2021-07-14 01:43 UTC, cos18 requested changes

2021-07-14 01:43 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.stories.tsx
> +
onChange를 이용해 Typo 안 값을 바꾸는 스토리를 만드시면 좋을것 같아요.

2021-07-14 01:43 UTC, cos18 commented on front/src/interfaces/atoms/TextInput/ITextInput.ts
> +                              "time" | "url" | "week";
HTML5에 쓰이는 모든 input type을 정의하는게 아니라 텍스트만 들고오는 타입만 넣으면 좋을 것 같아요.

2021-07-14 01:43 UTC, cos18 commented on front/src/components/atoms/TextInput/TextInput.stories.tsx
> +      ></TextInput>
스토리를 인터렉티브하게 만드는게 좋아요. 스토리북 컨트롤 메뉴에서 체크박스를 체크하는식으로 error 프롭을 관리하면 좋을 것 같아요

2021-07-14 06:16 UTC, merged