feat: Page/channel setting
404-DriverNotFound/team-a pull request #99
Opened 2021-08-03 06:17 UTC by kmin-283

- [x] channel-setting-item 구현
- [x] channel-setting-list 구현
- [x] channel-setting-page 구현
![1](https://user-images.githubusercontent.com/63279334/127966987-4cca40b8-ed34-4d02-b934-e4b234a2e244.jpg)
![2](https://user-images.githubusercontent.com/63279334/127966990-cbfa8fea-ad2b-4e84-ace3-af5e8ff3f85f.jpg)
# 주의사항
아직 채널의 인터페이스가 정의되지 않았으므로 임시로 id와 member를 추가해 둔 상황입니다.

이후 백엔드와 함께 인터페이스를 구체적으로 정의한 뒤 변경해야 합니다.

2021-08-03 07:31 UTC, cos18 requested changes

2021-08-03 07:31 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +const ChannelSettingPage = (): React.ReactElement => {
채널 세팅의 경우 어드민 유저인 경우에만 접근 가능하게 수정하셔야 합니다.

2021-08-03 07:31 UTC, cos18 commented on front/src/components/molecules/ChannelSettingItem/ChannelSettingItem.tsx
> +          }
현재 관리자 임명 / 해제의 대해서는 유저가 owner일 때만 처리할 수 있도록 작동해야합니다. 이에 대한 조건이 필요해보입니다.

2021-08-03 07:31 UTC, cos18 commented on front/src/components/molecules/ChannelSettingItem/ChannelSettingItem.tsx
> +            <InfoGrid title="이름" info={name} />
<img width="477" alt="Screen Shot 2021-08-03 at 4 20 41 PM" src="https://user-images.githubusercontent.com/33975709/127974408-f8d499c6-01aa-4e20-ae43-0e50a105109a.png">

호버했을때 위치가 좀 이상하게 보이는데 수정 가능하신가요?

2021-08-03 07:31 UTC, cos18 commented on front/src/components/molecules/FormDialog/FormDialog.stories.tsx
> +    console.log(open);
콘솔로그 말고 action으로 수정해주세요

2021-08-03 07:31 UTC, cos18 commented on front/src/components/molecules/FormDialog/FormDialog.tsx
> +    },
이렇게 마크와 최소 최대값이 정해져있으면 FormDialog가 아니라 MuteDialog로 네이밍 수정하는게 좋지 않을까요?

2021-08-03 07:31 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +    <Grid className={classes.root} container>
비밀번호를 변경하는 페이지도 있어야되서, 이걸 커뮤니티나 채널페이지처럼 메뉴가 필요해보입니다.

2021-08-03 07:31 UTC, cos18 commented on front/src/interfaces/molecules/ChannelSettingItem/IChannelSettingItem.ts
> +    appointAdmin: () => void;
appointAdmin 보단 setAdmin이 더 직관적이지 않을까요?

2021-08-03 15:07 UTC, kmin-283 commented on front/src/components/molecules/FormDialog/FormDialog.tsx
> +    },
아하 이건 mark를 props로 받는걸로 처리하려던 걸 깜빡했습니다!

2021-08-04 01:59 UTC, cos18 requested changes

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  }
이 조건문은 useEffect를 통해 정보를 fetch한 이후에 작동되야하는거 아닌가요?

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  const [type, setType] = useState('user');
더욱 명확한 네이밍 부탁드립니다.

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +              />
채널을 수정할 떄엔 채널 이름 변경 정의가 제외되어있습니다. 비밀번호 변경만 필요합니다.

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  return (
로딩중일때 로딩 컴포넌트가 보이게 추가해주세요.

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +      </Grid>
owner일떄에만 비밀번호 수정이 가능합니다. 오너일떄에만 이 메뉴가 보이도록 해주세요

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +      <Typo variant="h3">{channel?.name}</Typo>
```suggestion
      <Typo variant="h5">{channel?.name}</Typo>
```

채널 이름 표시를 좀 더 작게 해주세요.

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +            adminUserIds={channel?.adminUserIds}
이줄에서 null check를 할 이유가 있나요?

2021-08-04 01:59 UTC, cos18 commented on front/src/interfaces/molecules/ChannelSettingItem/IChannelSettingItem.ts
> +    unSetAdmin: () => void;
```suggestion
    unsetAdmin: () => void;
```
unset도 하나의 단어입니다. 카멜케이스로 네이밍 하면 위와 같이 수정하는게 좋을 것 같아요

2021-08-04 01:59 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  }
그리고 "접근할 수 없는 페이지입니다"와 같이 안내가 같이 필요해보입니다.

2021-08-04 02:04 UTC, kmin-283 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  }
맨 처음에 useEffect 내부에 집어넣었었는데 로그를 찍어보니까 계속 혼자서 랜더링이 일어나서 밖으로 뺏습니다 ㅠㅠ

지속적인 랜더링이 setTimeout때문에 일어나는건지 이후에 axios로 바꿔도 같은 현상이 일어날진 모르겠습니다..


우선 useEffect로 정보를 얻은 이후로 변경해두고 이슈에 등록해두겠습니다!

2021-08-04 02:11 UTC, cos18 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +  }
이건 이슈로 넣지 마시고 지금 수정하셔야 되요. settimeout 콜백함수 안에 넣어놨나요?

2021-08-04 02:30 UTC, kmin-283 commented on front/src/components/pages/ChannelSettingPage/ChannelSettingPage.tsx
> +      </Grid>
이 부분은
```
channel?.owner === user.id
```
로 처리해두었습니다!

2021-08-04 04:56 UTC, cos18 approved these changes

2021-08-04 04:57 UTC, merged